# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "CELEBRITY" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"source" VARCHAR,"name" VARCHAR,"givenName" VARCHAR,"lastName" VARCHAR,"birthDate" VARCHAR,"birthPlaceLabel" VARCHAR,"abstractText" VARCHAR,"thumbnail" VARCHAR,"children" VARCHAR,"height" VARCHAR,"residence" VARCHAR);

# --- !Downs

drop table "CELEBRITY";

